version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "7000:7000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:9.5
#    ports:
#      - "35432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
